In [8]:
import numpy as np

In [18]:
names = np.array(['bob','joy','medhi','nazo','khalil','muq','bilal'])

In [19]:
data= np.random.randn(7,4)

In [20]:
data

array([[ 0.44038367, -1.68156364, -1.13361703, -0.50324197],
       [ 0.73235201,  0.42639113,  0.95458815, -0.72203091],
       [ 0.58711563, -2.981484  ,  1.95793775, -0.49544559],
       [ 1.71166439,  1.35143787,  0.34670237,  0.61104035],
       [ 2.28041896,  1.26774694,  1.01687181,  1.97429875],
       [-0.23300555, -0.1916636 , -0.406567  ,  0.24830533],
       [ 0.16867212, -0.31760167, -1.24729295, -0.0548638 ]])

In [21]:
names == 'bob'

array([ True, False, False, False, False, False, False])

In [22]:
data[names == 'bob']

array([[ 0.44038367, -1.68156364, -1.13361703, -0.50324197]])

In [23]:
data[names != 'bob']

array([[ 0.73235201,  0.42639113,  0.95458815, -0.72203091],
       [ 0.58711563, -2.981484  ,  1.95793775, -0.49544559],
       [ 1.71166439,  1.35143787,  0.34670237,  0.61104035],
       [ 2.28041896,  1.26774694,  1.01687181,  1.97429875],
       [-0.23300555, -0.1916636 , -0.406567  ,  0.24830533],
       [ 0.16867212, -0.31760167, -1.24729295, -0.0548638 ]])

In [25]:
data[names == 'bob' ,2:]

array([[-1.13361703, -0.50324197]])