In [3]:
a=[2,4,6,8,10]

In [5]:
b =[]
for num in a:
    b.append(2*num)
b    

[4, 8, 12, 16, 20]

In [6]:
import numpy as np

In [7]:
a= np.array([1,3,4,5,6,7,8,9,10])

In [8]:
type(a)

numpy.ndarray

In [9]:
2*a

array([ 2,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
data = np.random.randn(2,3)
data

array([[-0.27279338, -0.73824903,  0.45094644],
       [ 1.28953337,  0.44281357,  0.03508836]])

In [11]:
data1 = np.arange(10)

In [12]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
data1.ndim

1

In [16]:
# One Demention is called Vector 

In [ ]:
# Two Demention is called Matrix

In [17]:
data.shape

(2, 3)

In [18]:
data1.shape

(10,)

In [25]:
m= np.array([100])

In [30]:
m.ndim

1

In [34]:
n= np.array([[[[[[[[[[[[100]]]]]]]]]]]])

In [35]:
n.ndim

12

In [36]:
n.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

In [37]:
_3d = np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
_3d

array([[[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]]])

In [38]:
threeD = np.arange(64).reshape(4,4,4)
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [40]:
threeD = np.arange(30).reshape(2,5,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [41]:
threeD.ndim


3

In [51]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9],[4,3,2]])

In [52]:
m1.shape == m2.shape

True

In [53]:
m1+m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [13, 13, 13]])

In [54]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 5,  7,  9]])

In [55]:
m1*m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 30, 22]])

In [50]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [2.25      , 3.33333333, 5.5       ]])

In [58]:
print(m1.shape)
print(m2.shape)
m1@m2

(4, 3)
(4, 3)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [62]:
a= np.array([33,44,55],dtype="float32")
a



array([33., 44., 55.], dtype=float32)

In [63]:
np.asarray("int32")

array('int32', dtype='<U5')

In [64]:
b= np.asarray(a,"int32")
b

array([33, 44, 55])

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.empty(6)

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313,
       8.48798317e-314, 4.24399158e-314])

In [82]:
aa=np.full((10,10),7)
aa

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [83]:
np.ones_like(aa)


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [84]:
alist= [1,2,3,4,5,6,7]

In [85]:
alist[4]

5

In [89]:
type(alist[3])

int

In [90]:
type(alist[2:4])

list

In [91]:
td = np.arange(36).reshape(6,6)

In [92]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [93]:
td[2,3] # is called indexing

15

In [94]:
td[2][3] # is called indexing

15

In [95]:
#td [r,c]
#td [--,--]
td[2:5,2:4]

array([[14, 15],
       [20, 21],
       [26, 27]])